import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/Menu";
import { Sidebar } from "@/components/Sidebar";
import { budgets } from "@/data/budgets";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SaaS 01",
  description: "Generated by lusbnz.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="block hide-scrollbar">
          <Menu />
          <div className="border-t">
            <div className="bg-background">
              <div className="grid lg:grid-cols-5">
                <Sidebar budgets={budgets} className="hidden lg:block" />
                <div className="col-span-3 lg:col-span-4 lg:border-l">
                  {children}
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
